import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { AnyOperation } from './operation.js';

/** A labeled set of operations for the capability table: its provenance + the ops. */
export type CapabilityGroup<Client> = {
  /** Provenance shown in the Source column. */
  kind: CapabilityKind;
  operations: Record<string, AnyOperation<Client>>;
};

/** The two provenance kinds a capability group can carry (Google's two reference trees). */
export type CapabilityKind = 'MCP Tool' | 'REST Method';

/** Prose labels for the group kinds; the header sentence is built from these. */
const KIND_LABELS: Record<CapabilityKind, string> = {
  'MCP Tool': 'MCP tools',
  'REST Method': 'REST methods',
};

/**
 * Render the operations as a Markdown capability table (name, source, description,
 * and a destructive marker), derived from the same registries the server
 * dispatches. The Source column makes the provenance explicit: a service is an
 * MCP-toolset wrapper and a REST wrapper (or REST only, where Google publishes
 * no toolset), because MCP's toolset alone cannot fully drive a service. A
 * static mirror; agents that speak MCP discover the live, fully-schema'd
 * surface via `tools/list`. Pure; a service regenerates its CAPABILITIES.md
 * from this (and a test pins the file to it) so the doc cannot drift from the code.
 */
export function renderCapabilities<Client>(
  title: string,
  groups: CapabilityGroup<Client>[],
): string {
  const rows = groups.flatMap(({ kind, operations }) =>
    Object.entries(operations).map(
      ([name, op]) =>
        `| [\`${name}\`](${op.source})${op.annotations.destructiveHint ? ' ⚠️' : ''} | ${kind} | ${op.description} |`,
    ),
  );
  // Derived from the groups actually passed in, so a methods-only service
  // (Sheets, Docs) does not claim an MCP toolset it does not have.
  const labels = groups.map(({ kind }) => KIND_LABELS[kind]);
  const sources = labels.length === 1 ? `, all ${labels[0]}` : ` across ${labels.join(' and ')}`;
  return `${[
    `# ${title}`,
    '',
    '<!-- Generated by `bun run capabilities`; do not edit by hand. -->',
    '',
    `${rows.length} operations${sources}. ⚠️ marks destructive operations (MCP \`destructiveHint\`): removals, sends, and standing side effects.`,
    '',
    '| Operation | Source | Description |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n')}\n`;
}

/**
 * Write CAPABILITIES.md beside the calling bootstrap module: each service's
 * `capabilities.ts` passes its own `import.meta.url`, so the doc always lands
 * next to the registries it renders, and the wing's equality test can pin the
 * committed file to `renderCapabilities` of the live registries.
 */
export function writeCapabilities<Client>(
  moduleUrl: string,
  title: string,
  groups: CapabilityGroup<Client>[],
): void {
  const out = fileURLToPath(new URL('./CAPABILITIES.md', moduleUrl));
  writeFileSync(out, renderCapabilities(title, groups));
  const count = groups.reduce((n, group) => n + Object.keys(group.operations).length, 0);
  console.error(`Wrote CAPABILITIES.md (${count} operations)`);
}
